#!/bin/sh
#
red='\033[31m\033[01m'
green='\033[32m\033[01m'
yellow='\033[33m\033[01m'
plain='\033[0m'

echo -e "${green}x-ui安装使用的是原版，脚本只是让x-ui运行到Alpine，并自动设置开机自启"
echo -e "${red}x-ui面板命令无效，请打开web管理操作"
echo -e "${green}用户名密码admin，port9000"
echo -e "${yellow}安全起见，安装两遍！"

echo "x-ui install for alpine"
echo "检查安装环境"
apk add curl && apk add bash && apk add sudo && apk add wget
mkdir /lib64
cp /lib/ld-musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

install_x-ui() {
echo "安装Alpine所需文件"
curl -Ls https://github.com/kkddcclloo/x-ui/raw/main/xuidb/x-ui.db -o x-ui.db
curl -Ls https://github.com/kkddcclloo/x-ui/raw/main/xuidb/config.json -o config.json
curl -Ls https://github.com/kkddcclloo/x-ui/raw/main/xuidb/x-ui -o x-ui
mv x-ui.db /etc/x-ui/
mv x-ui /etc/init.d/
mv config.json  /usr/local/x-ui/bin/
chown 501.dialout /etc/x-ui/x-ui.db
chown 501.dialout /usr/local/x-ui/bin/config.json
chmod +x /etc/init.d/x-ui
chmod 0644 /etc/x-ui/x-ui.db
chmod 0644 /usr/local/x-ui/bin/config.json
rc-update add /etc/init.d/x-ui
echo "启动x-ui服务，可以ctrl+z退出"
/etc/init.d/x-ui start
bash <(curl -Ls https://raw.githubusercontent.com/vaxilu/x-ui/master/install.sh)
Configuration
}

Configuration(){
#/usr/local/x-ui/x-ui setting -username admin -password admin -port 9000
echo "用户名admin,密码admin,端口9000(访问注意映射)"
/etc/init.d/x-ui restart
rc-update add sshd
rc-service sshd restart
echo "安装完成"
}

set_port() {
       echo && echo -n -e "输入端口号[1-65535]: " && read port
       if [[ -z "${port}" ]]; then
            LOGD "已取消"
       else
           /usr/local/x-ui/x-ui setting -port ${port}
           echo -e "设置端口完毕，现在请重启面板，并使用新设置的端口 ${green}${port}${plain} 访问面板"
           /etc/init.d/x-ui restart
       fi
}

show_menu() {
    echo -e "
  ${green}安装x-ui${plain}
  ${green}0.${plain} 退出脚本
————————————————
  ${green}1.${plain} 安装原版x-ui
  ${green}2.${plain} 重新设置面板端口
 "
    echo && read -p "请输入选择 [0-2]: " num

    case "${num}" in
    0)
        exit 0
        ;;
    1)
        install_x-ui
        ;;
    2)
        set_port
        ;; 
    *)
        LOGE "请输入正确的数字 [0-2]"
        ;;
    esac
}
    show_menu
